import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  MenuIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  DotsVerticalIcon,
  PlusIcon,
  MoonIcon,
  SunIcon,
} from "@heroicons/react/solid";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Filler,
  Legend,
  ChartData,
} from "chart.js";
import { Line } from "react-chartjs-2";
import { useState } from "react";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Filler,
  Legend
);

const options = {
  responsive: true,
  plugins: {
    legend: {
      display: false,
    },
  },
  scales: {
    y: {
      max: 27,
      min: 25,
      ticks: {
        stepSize: 1,
      },
      grid: {
        display: true,
        drawBorder: false,
        color: function (context: any) {
          return "rgba(255,255,255,0.1)";
        },
      },
    },
  },
};

const labels = ["14:00", "14:10", "14:20"];
const data: ChartData<"line", number[], string> = {
  labels,
  datasets: [
    {
      fill: true,
      label: "Dataset 2",
      data: [25, 26, 26],
      borderColor: "#ddd",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      borderWidth: 1,
      pointBorderWidth: 0,
    },
  ],
};

const Index: NextPage = () => {
  const [temp, setTemp] = useState(26);
  const [status, setStatus] = useState(false);
  const [theme, setThme] = useState<"light" | "dark">("light");

  const handleTempChange = (mode: "add" | "sub") => {
    if (mode === "add") {
      temp < 30 && setTemp(temp + 1);
    } else {
      temp > 20 && setTemp(temp - 1);
    }
  };

  return (
    <div className="relative h-full">
      <Head>
        <title>Control</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="dark:text-white">
        <div className="flex items-center p-2 py-5">
          <MenuIcon className="w-8 h-8"></MenuIcon>
          <span className="ml-3 text-3xl font-semibold">IR Remote</span>

          <span
            className="ml-auto mr-3"
            onClick={() => {
              if (theme === "dark") {
                setThme("light");
                document.documentElement.classList.remove("dark");
                document.body.style.background = "white";
              } else {
                setThme("dark");
                document.documentElement.classList.add("dark");
                document.body.style.background = "black";
              }
            }}
          >
            {theme === "light" ? (
              <MoonIcon className="w-8 h-8"></MoonIcon>
            ) : (
              <SunIcon className="w-8 h-8"></SunIcon>
            )}
          </span>
        </div>

        <div className="bg-gray-100 dark:bg-[rgba(28,28,28,0.9)] mx-3 mt-5 rounded-3xl p-5">
          <div className="flex items-center justify-between">
            <div className="w-1/3">
              <div className="text-md">Current Temp</div>
              <div className="my-2 text-5xl">{temp}˚</div>
              <div className=" text-black/40 dark:text-white/40 text-md">
                10 Min ago
              </div>
            </div>

            <div className="w-2/3 pl-10">
              <Line data={data} options={options}></Line>
            </div>
          </div>
        </div>

        <div className="bg-gray-100 dark:bg-[rgba(28,28,28,0.9)] mx-3 mt-5 rounded-3xl p-5">
          <div className="flex items-center justify-around">
            <div
              className="flex flex-col items-center"
              onClick={() => handleTempChange("sub")}
            >
              <span className="p-2 bg-black rounded-full">
                <ChevronLeftIcon className="w-10 h-10 text-white dark:text-white/50 active:text-white/70"></ChevronLeftIcon>
              </span>
              <div className="mt-2 text-xs dark:text-white/40">Low</div>
            </div>

            <span
              className="flex flex-col p-2 rounded-full"
              style={{
                background: status
                  ? "#fff"
                  : theme === "dark"
                  ? "#888"
                  : "rgba(229,231,235)",
              }}
              onClick={() => {
                setStatus(!status);
              }}
            >
              {status && (
                <span className="w-10 h-10 px-3 bg-black rounded-full "></span>
              )}

              <span className="flex items-center justify-center w-10 h-10 px-3 font-bold text-black rounded-full">
                {status ? "On" : "Off"}
              </span>
              {!status && (
                <span className="w-10 h-10 px-3 bg-black rounded-full "></span>
              )}
            </span>
            <div
              className="flex flex-col items-center"
              onClick={() => handleTempChange("add")}
            >
              <span className="p-2 bg-black rounded-full">
                <ChevronRightIcon className="w-10 h-10 text-white dark:text-white/50 active:text-white/70"></ChevronRightIcon>
              </span>
              <div className="mt-2 text-xs dark:text-white/40">High</div>
            </div>
          </div>
        </div>

        <div className="flex">
          <div className="bg-gray-100 dark:bg-[rgba(28,28,28,0.9)] mx-3 mt-5 rounded-3xl p-5 flex-1">
            <div className="flex">
              <span>Time On</span>
              <span className="ml-auto text-black/30 dark:text-white/50">
                ◎
              </span>
            </div>

            <div className="flex justify-center mt-5 text-xl">
              <div className="flex flex-col items-end w-full">
                <div className="flex w-full p-2 text-xs bg-gray-200 rounded-xl text-black/50 dark:bg-white/10 dark:text-white/70">
                  <span>No task</span>
                  <span className="ml-auto">+</span>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-gray-100 dark:bg-[rgba(28,28,28,0.9)] mx-3 mt-5 rounded-3xl p-5 flex-1">
            <div className="flex">
              <span>Time Off</span>
              <span className="ml-auto text-black/30 dark:text-white/50">
                ◎
              </span>
            </div>
            <div className="flex justify-center mt-5 text-xl">
              <div className="flex flex-col items-end w-full">
                <div className="flex w-full p-2 text-xs bg-gray-200 rounded-xl text-black/50 dark:bg-white/10 dark:text-white/70">
                  <span>After 10 min</span>
                  <span className="ml-auto">-</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-gray-100 dark:bg-[rgba(28,28,28,0.9)] mx-3 mt-5 rounded-3xl p-5 flex justify-center ">
          <span className="p-2 bg-black rounded-full">
            <PlusIcon className="w-12 h-12 text-white dark:text-white/50 active:text-white/70"></PlusIcon>
          </span>
        </div>
      </div>

      <footer className="mt-16 mb-5 text-sm text-center text-black/30 dark:text-white/30">
        <div>Design by DeadRabbit</div>
      </footer>
    </div>
  );
};

export default Index;
